export const ADD_INCOME = 'ADD_INCOME';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_SORTBY = 'CHANGE_SORTBY';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const INITIATE_SETUP = 'INITIATE_SETUP';
